version: '3.8'

services:
  vins-fusion:
    image: lukechen01/vins-humble-arm64:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile-arm64
    container_name: vins-fusion-humble-arm64
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../:/root/colcon_ws/src
      - /home/${USER}/guofei/dexcontrol:/root/dexcontrol:rw
      - /home/${USER}/guofei/dexsensor:/root/dexsensor:rw
      - /dev:/dev
      
    # disabled for ros2 communication. See: https://github.com/eProsima/Fast-DDS/issues/5396#issuecomment-2493358758
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    working_dir: /root/colcon_ws
    # Enabling Nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]